### ISSUE TITLE
Mutex<UnsafeCell>是否冗余？

### ISSUE THREAD

**Issue by LaoLittle** [kgagag/tomato#3]
<img width="868" alt="Screenshot 2024-05-02 at 23 32 17" src="https://github.com/kgagag/tomato/assets/93422095/b61646eb-b5fd-4de3-a72b-ceb0d7d711e9">

Mutex本身就是具有内部可变性的结构，lock之后可获取mutable reference，请问再套一层unsafecell的意义在哪里呢？

**Comment by kgagag** [comment]
确实冗余了，我不太会rust，很多代码都是gpt帮我写的，我抽空会学习一下rust的知识，然后重构一下

**Comment by LaoLittle** [comment]
> 确实冗余了，我不太会rust，很多代码都是gpt帮我写的，我抽空会学习一下rust的知识，然后重构一下

加油，看出来很大一部分是用C/C++思维在写，很多unsafe其实是不必要的

项目本身则很值得学习

**Comment by kgagag** [comment]
感谢指导，已经开始使用clippy 扫描了，正在解决扫描出现的问题
